language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - sys-img-x86_64-addon-google_apis-google-25

notifications:
    email:
        - alessandro.crugnola@gmail.com

cache: false
sudo: false

env:
  global:
  # install timeout in minutes (2 minutes by default)
  - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-25 --abi google_apis/x86_64
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - android update sdk -u -a --filter platform-tools-25.0.1

install:
    - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

script:
  - android list target
  - ./gradlew build connectedCheck -PdisablePreDex


